### ISSUE TITLE
Not working on codeigniter 3.

### ISSUE THREAD

**Issue by noluong** [lonnieezell/codeigniter-forensics#22]
I have setting all step you wrote.
I setting:
$autoload['packages'] = array(APPPATH.'third_party/codeigniter-forensics');

But it seem do not working. 
I don't know why ?  
Please help me.

**Comment by lonnieezell** [comment]
Looks like some recent changes to CI 3 have made it so that packages cannot override core libraries. I have filed a bug report with them to see if that was intentional or not.

In the meantime you should be able to move the files into their normal application folders - so move Profiler.php to libraries and the view file into the view folder.

**Comment by noluong** [comment]
Yes. I got it. 
I moved Profiler.php to libraries and the view file into the view folder and it working.
Thank you very much.

**Comment by lonnieezell** [comment]
Just as an update, the main CodeIgniter branch was just updated to allow for packages to override system libraries now, so this should be back up and working.
